version: '3'

services:
  db:
    container_name: netflixprj_mysql
    image: mysql:8.0
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${MYSQL_DB}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ${WEBAPP_STORAGE_HOME}/mysql:/var/lib/mysql
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"

  web:
    depends_on:
      - db
    image: netflixprj.azurecr.io/netflixprj-django:latest
    container_name: netflixprj_django
    restart: always
    volumes:
      - ${WEBAPP_STORAGE_HOME}/media:/src/media
      - static-volume:/src/static
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    environment:
      - MYSQL_DB=${MYSQL_DB}
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      
  nginx:
    depends_on:
      - web
    image: netflixprj.azurecr.io/netflixprj-nginx:latest
    container_name: netflixprj_nginx
    restart: always
    ports:
      - 8000:80
    volumes:
      - static-volume:/static
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
volumes:
  static-volume:
