version: '3'

services:
  web:
    image: netflixprj.azurecr.io/netflixprj-django:latest
    container_name: netflixprj_django
    restart: always
    volumes:
      - media-volume:/src/media
      - static-volume:/src/static
      - sqlite3-volume:/src/db
  nginx:
    depends_on:
      - web
    image: netflixprj.azurecr.io/netflixprj-nginx:latest
    container_name: netflixprj_nginx
    restart: always
    ports:
      - 8000:80
    volumes:
      - static-volume:/static:ro
volumes:
  media-volume:
  static-volume:
  sqlite3-volume:
