version: '3'

services:
  web:
    build: ./netflixprj
    container_name: netflixprj_django
    restart: always
    volumes:
      - media-volume:/src/media
      - static-volume:/src/static
      - sqlite3-volume:/src/db
  nginx:
    depends_on:
      - web
    build: ./custom_nginx
    container_name: netflixprj_nginx
    restart: always
    ports:
      - 8000:80
    volumes:
      - static-volume:/static
volumes:
  media-volume:
  static-volume:
  sqlite3-volume:
