name: Docker Image CI

on:
  push:
    branches: [ "containerized" ]
  pull_request:
    branches: [ "containerized" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build django 
      run: docker build ./netflixprj --file Dockerfile --tag netflixprj-django:$(date +%s)
    - name: Build nginx
      run: docker build ./custom_nginx --file Dockerfile --tag netflixprj-ngnix:$(date +%s)
